UPDATE videos SET title = 'David in the City 1' WHERE id = 82;
UPDATE videos SET title = 'David in the City 2' WHERE id = 83;
UPDATE videos SET title = 'David in the City 3' WHERE id = 84;
UPDATE videos SET title = 'David in the City 4' WHERE id = 85;
UPDATE videos SET title = 'David in the City 5' WHERE id = 86;
UPDATE videos SET title = 'David in the City 6' WHERE id = 87;
UPDATE videos SET title = 'David in the City 7' WHERE id = 88;
UPDATE videos SET title = 'David in the City 8' WHERE id = 89;
UPDATE videos SET title = 'David in the City 9' WHERE id = 90;
UPDATE videos SET title = 'David in the City 10' WHERE id = 91;
UPDATE videos SET title = 'David in the City 11' WHERE id = 92;
UPDATE videos SET title = 'David in the City 12' WHERE id = 93;
UPDATE videos SET title = 'K-Town 1' WHERE id = 94;
UPDATE videos SET title = 'K-Town 2' WHERE id = 95;
UPDATE videos SET title = 'K-Town 3' WHERE id = 96;
UPDATE videos SET title = 'K-Town 4' WHERE id = 97;
UPDATE videos SET title = 'K-Town 5' WHERE id = 98;
UPDATE videos SET title = 'K-Town 6' WHERE id = 99;
UPDATE videos SET title = 'K-Town 7' WHERE id = 100;
UPDATE videos SET title = 'K-Town 8' WHERE id = 101;
UPDATE videos SET title = 'K-Town 9' WHERE id = 102;
UPDATE videos SET title = 'K-Town 7' WHERE id = 100;
